on:
  workflow_dispatch:
  push:
    branches: 
      - design
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'design'
    - name: create env for build
      run: | 
        mv .env.copy .env
        sed -i 's/http:\/\/localhost:26657/https:\/\/${{ secrets.HOST }}:26657/g' .env
        sed -i 's/http:\/\/localhost:1317/https:\/\/${{ secrets.HOST }}:1317/g' .env
        sed -i 's/ws:\/\/localhost/wss:\/\/${{ secrets.HOST }}/g' .env
    - run: cat .env    
    - name: Use Node.js 15
      uses: actions/setup-node@v1
      with:
        node-version: '15'
    - name: install dependences
      run: npm install --global expo-cli
    - run: npm install
    - run: expo build:web
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        target: 'meta-belarus-id-github'
